# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.wallbox: debug
    custom_components.wallbox.wallbox: debug
# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
#debugpy:
  #start: true
  #wait: true
  #port: 5678

